bias = 0.01
weights = [
    0.15,
    0.12,
    0.1,
    0.08,
    0.05,
    0.03,
    0.02,
    0.01,
    -0.01,
    -0.02,
    -0.03,
    -0.05,
    -0.08,
    -0.1,
    -0.12,
    -0.15,
    -0.18,
    -0.2,
    -0.22,
    -0.25,
]
